# Generated by Django 5.2 on 2025-07-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_title", models.CharField(max_length=255)),
                ("helpfulness", models.CharField(max_length=50)),
                ("comments", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
